# Generated by Django 2.2.7 on 2019-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image only if needed for Question.', null=True, upload_to='question_images'),
        ),
    ]
